name: My First Workflow

on: push

jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
            - name: checkout Repo
              uses: actions/checkout@v4
            
            - name: List and Read file
              run: |
                echo "My First GitHub Action Job"
                ls -ltra
                cat README.md
            
            - name: Generate  ASCII Artwork
              run: cowsay -f dragon "Run for cover, i am a LION.. ROAR" >> lion.txt
              
            # - name: List files
            #   run: ls

            # - name: Read file
            #   run: cat README.md
